config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
  	root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
belongs_to :user

app/models/doc.rb
class Doc < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
  	@docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
  	@doc = current_user.docs.build
  end

  def create
  	@doc = current_user.docs.build(doc_params)

	if @doc.save
		redirect_to @doc
	else
		render 'new'
	end
  end

  def edit
  end

  def update
	if @doc.update(doc_params)
		redirect_to @doc
	else
		render 'edit'
    end			
  end

  def destroy
	@doc.destroy
	redirect_to docs_path
  end

  private 

  def find_doc
 	@doc = Doc.find(params[:id])
  end
 
   def doc_params
   	params.require(:doc).permit(:title,:content)
   end
 
	
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authentications/_form.html.erb
<%= simple_form_for(@authentication) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :provider %>
    <%= f.input :uid %>
    <%= f.input :index %>
    <%= f.input :create %>
    <%= f.input :destroy %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing Authentication</h1>

<%= render 'form', authentication: @authentication %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authentications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Provider</th>
      <th>Uid</th>
      <th>Index</th>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authentications.each do |authentication| %>
      <tr>
        <td><%= authentication.user_id %></td>
        <td><%= authentication.provider %></td>
        <td><%= authentication.uid %></td>
        <td><%= authentication.index %></td>
        <td><%= authentication.create %></td>
        <td><%= authentication.destroy %></td>
        <td><%= link_to 'Show', authentication %></td>
        <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
        <td><%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New Authentication</h1>
<%= render 'form', authentication: @authentication %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>User:</strong>
  <%= @authentication.user_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @authentication.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @authentication.uid %>
</p>

<p>
  <strong>Index:</strong>
  <%= @authentication.index %>
</p>

<p>
  <strong>Create:</strong>
  <%= @authentication.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @authentication.destroy %>
</p>

<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

app/views/docs/edit.html.haml
%h1 Fix Doc!

= render 'form'

= link_to "Cancel", doc_path

app/views/docs/index.html.haml
- @docs.each do |doc|
  %h2= link_to doc.title, doc
  %p= time_ago_in_words(doc.created_at)
  %p= truncate(doc.content, length:50)

= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
%h1 New Doc!

= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content

= link_to "All Docs", docs_path
= link_to "Fix Doc", edit_doc_path(@doc)
= link_to "Trash It", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?"}

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileCabinet | Your life's work!
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to "FileCabinet", root_path, id: "logo"

      %nav 
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out",destroy_user_session_path, method: :delete

        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield



  

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Your life's work. Organized, always.
    %button= link_to "Enter", new_user_registration_path
#callouts
  .callouts_inner
    .wrapper
      .callout
        %h2 Organize
        %p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

#bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br
    %button= link_to "Join Now", new_user_registration_path